name: CI

on:
  push:
    branches:
      - main

jobs:
  curl-tailnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          # oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          # oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          # tags: tag:ci
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Curl
        run: curl 10.128.0.5