name: CI

on:
  push:
    branches:
      - main
      - oauth

jobs:
  curl-tailnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Curl
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}" -m 30 10.128.0.5)
          if [[ $response -eq 200 ]]; then
            echo "Response is 200"
          else
            echo "Response is not 200"
            exit 1
          fi
          